# Generated by Django 5.0.2 on 2024-03-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cerveza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=60)),
                ('color', models.CharField(max_length=10)),
                ('ibu', models.CharField(max_length=5)),
                ('alcohol', models.CharField(max_length=4)),
                ('cantMl', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ginebra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=60)),
                ('regionOrigen', models.CharField(max_length=60)),
                ('alcohol', models.CharField(max_length=4)),
                ('cantMl', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mezcal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=60)),
                ('tipoAgave', models.CharField(max_length=60)),
                ('clasificacion', models.CharField(max_length=20)),
                ('alcohol', models.CharField(max_length=4)),
                ('cantMl', models.IntegerField()),
            ],
        ),
    ]
